title: Ali Kazemi
description: Researcher in Biomedical AI & Computational Neuroscience | Machine Learning, Medical Imaging & Neural Signals | Seeking a Funded PhD
theme: jekyll-theme-cayman
show_downloads: false
